### ISSUE TITLE
More documenting required on scripting.

### ISSUE THREAD

**Issue by Saegusae** [tera-alkahest/alkahest#17]
Yo seems you have the foundations of a scripting API with python working but there is literally no documentation on it except the tiny example mod :p

**Comment by alexrp** [comment]
Python scripts use the exact same APIs as C# plugins, so the `simple-test` plugin serves as documentation: https://github.com/alexrp/alkahest/blob/master/Alkahest.Plugins.SimpleTest/SimpleTestPlugin.cs

**Comment by alexrp** [comment]
I'll add a wiki page with an overview of `Alkahest.Core` APIs at some point though.

**Comment by alexrp** [comment]
@Saegusae I know this issue is pretty old, but do you have anything in particular that you feel is missing in documentation? I've fleshed out the wiki pages a little more:

* https://github.com/tera-alkahest/alkahest/wiki/Plugin-Development
* https://github.com/tera-alkahest/alkahest/wiki/Script-Development

**Comment by alexrp** [comment]
Closing for now due to lack of response.
